version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

  app:
    build: .
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/api-task?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
